name: .NET Build + Test + Publish

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  build:
    runs-on: windows-2022

    steps:
      - uses: actions/checkout@v4
      - name: Setup .NET
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: 8.0.x
      - name: Restore dependencies
        run: dotnet restore
      - name: Build
        if: ${{ github.event_name != 'pull_request' }}
        run: dotnet build --no-restore  --configuration Release -p:PostBuildEvent=
      - name: Upload artifact
        uses: actions/upload-artifact@v4
        if: ${{ github.event_name != 'pull_request' }}
        with:
          path: "AppImageManager/bin/Release/*.nupkg"
